// <auto-generated />
using LevelLegal.Domain.Entities.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LevelLegal.Domain.Entities.Migrations
{
    [DbContext(typeof(DataAccess))]
    partial class DataAccessModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LevelLegal.Domain.Entities.Models.Evidence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MatterId")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("MatterId");

                    b.ToTable("Evidences");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Dell XPS Laptop",
                            MatterId = 100,
                            SerialNumber = "DG56GSR"
                        },
                        new
                        {
                            Id = 2,
                            Description = "San Disk Flash Drive",
                            MatterId = 100,
                            SerialNumber = "43255323GS445344"
                        },
                        new
                        {
                            Id = 3,
                            Description = "ASUS Zenbook 14 Laptop",
                            MatterId = 100,
                            SerialNumber = "GBSFFDW8434-3323"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Kingston 256GB Flash Drive",
                            MatterId = 101,
                            SerialNumber = "KD43243KT67655"
                        },
                        new
                        {
                            Id = 5,
                            Description = "iPhone 15",
                            MatterId = 102,
                            SerialNumber = "GT453223FSTR52"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Samsung NVMe M2 Internal Drive",
                            MatterId = 102,
                            SerialNumber = "SE5324GYTF65556"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Samsung Fold Cell Phone",
                            MatterId = 102,
                            SerialNumber = "FSYGD645DFSWWSFFDTSAA"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Lacie External 1TB Drive",
                            MatterId = 103,
                            SerialNumber = "AD34222432-321321"
                        });
                });

            modelBuilder.Entity("LevelLegal.Domain.Entities.Models.Matter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Matters");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            Name = "Up vs Down"
                        },
                        new
                        {
                            Id = 101,
                            Name = "In vs Out"
                        },
                        new
                        {
                            Id = 102,
                            Name = "EF Core vs Dapper"
                        },
                        new
                        {
                            Id = 103,
                            Name = "Dark Mode vs Light Mode"
                        });
                });

            modelBuilder.Entity("LevelLegal.Domain.Entities.Models.Evidence", b =>
                {
                    b.HasOne("LevelLegal.Domain.Entities.Models.Matter", "Matter")
                        .WithMany("Evidences")
                        .HasForeignKey("MatterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Matter");
                });

            modelBuilder.Entity("LevelLegal.Domain.Entities.Models.Matter", b =>
                {
                    b.Navigation("Evidences");
                });
#pragma warning restore 612, 618
        }
    }
}
